export default [
  {
    id: "1",
    title: "1 Pote",
    parties: "30 doses/festas",
    price: "R$ 117,00",
    priceCard: "R$ 3,90 p/dose",
    installments: "12x R$ 11,75",
    img: "/img/packs/01-pack.png",
    link: "https://app.monetizze.com.br/checkout/DSM145062",
    linkBraip: "https://ev.braip.com/checkout/plakrlzl/cheodlk9",
    tag: "",
  },
  {
    id: "2",
    title: "2 + 1 Potes",
    parties: "90 doses/festas",
    priceCard: "R$ 2,60 p/dose",
    pricePocket: "R$ 78,00 p/pote",
    price: "R$ 234,00",
    installments: "12x R$ 23,49",
    img: "/img/packs/03-packs.png",
    link: "https://app.monetizze.com.br/checkout/DLN145084",
    linkBraip: "https://ev.braip.com/checkout/plazzp1z/che5jn1w",
    tag: "Frete Grátis para SP",
  },
  {
    id: "3",
    title: "3 + 3 Potes",
    parties: "180 doses/festas",
    priceCard: "R$ 1,95 p/dose",
    price: "R$ 351,00",
    pricePocket: "R$ 58,50 p/pote",
    installments: "12x R$ 35,24",
    img: "/img/packs/04-packs.png",
    link: "https://app.monetizze.com.br/checkout/DZD145085",
    linkBraip: "https://ev.braip.com/checkout/plagzdej/chek9vzd",
    tag: "Frete Grátis para todo o Brasil",
  },
  {
    id: "4",
    title: "5 + 7 Potes",
    parties: "360 doses/festas",
    priceCard: "R$ 1,62 p/dose",
    price: "R$ 585,00",
    pricePocket: "R$ 48,75 p/pote",
    installments: "12x R$ 58,74",
    img: "/img/packs/05-packs.png",
    link: "https://app.monetizze.com.br/checkout/DKF145089",
    linkBraip: "https://ev.braip.com/checkout/pla2r41e/chexp9rl",
    tag: "Frete Grátis para todo o Brasil",
  },
];
